import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import { SmoothScroll } from "@/components/ui/SmoothScroll";

export const metadata = {
  title: "Nemesys",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <SessionWrapper>
          <body className="min-h-full flex flex-col">
            <SmoothScroll>
              {children}
            </SmoothScroll>
          </body>
      </SessionWrapper>
    </html>
  );
}
